package me.kucoo.graph;

public enum QuestionType {
	FILM_WHOIS,
	FILM_GENRE,
	FILM_RELEASED_DATE,
	FILM_BUDGET,
	FILM_RUNTIME,
	FILM_STARRING_ACTORS,
	FILM_TITLE_WHOIS,
	FILM_TAGLINE,
	FILM_ACTOR_CHARACTER,
	FILM_COMBO
}
